import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import React from 'react'
import ReduxProvider from '@/redux/provider'

const inter = Inter({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	)
}
